// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4SsOAHKS42WcFCHX6Ujpp7wPlX0mw0CM',
    appId: '1:618930239431:web:6d841636ae6d9bd3f34be2',
    messagingSenderId: '618930239431',
    projectId: 'medical-booking-fd983',
    authDomain: 'medical-booking-fd983.firebaseapp.com',
    storageBucket: 'medical-booking-fd983.firebasestorage.app',
    measurementId: 'G-HVVX7VHWFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlx6mU70cka-b25xLchHfiLsYCM_J5glk',
    appId: '1:618930239431:android:f57f0313d47551e5f34be2',
    messagingSenderId: '618930239431',
    projectId: 'medical-booking-fd983',
    storageBucket: 'medical-booking-fd983.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAdILzoGx0a360pG6Jtbj13eyrswqOAm4',
    appId: '1:618930239431:ios:56919f8556dae997f34be2',
    messagingSenderId: '618930239431',
    projectId: 'medical-booking-fd983',
    storageBucket: 'medical-booking-fd983.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationDiva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAdILzoGx0a360pG6Jtbj13eyrswqOAm4',
    appId: '1:618930239431:ios:56919f8556dae997f34be2',
    messagingSenderId: '618930239431',
    projectId: 'medical-booking-fd983',
    storageBucket: 'medical-booking-fd983.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationDiva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4SsOAHKS42WcFCHX6Ujpp7wPlX0mw0CM',
    appId: '1:618930239431:web:79db350f8c8b911df34be2',
    messagingSenderId: '618930239431',
    projectId: 'medical-booking-fd983',
    authDomain: 'medical-booking-fd983.firebaseapp.com',
    storageBucket: 'medical-booking-fd983.firebasestorage.app',
    measurementId: 'G-Y1HE2ZW2YM',
  );
}
